all: README.md
	
README.md: guessinggame.sh makefile
	echo "## The Unix Workbench course assignment" > README.md
	echo "*by '[Johns Hopkins University](https://www.jhu.edu)' on **[Coursera](https://www.coursera.org/learn/unix/home/)**.*" >> README.md
	echo >> README.md
	echo "**Description**:" >> README.md 
	echo "This is an [my](https://www.coursera.org/user/c4eb72abf10b67a45cff50bd57d6b87e) assignment for [The Unix Workbench](https://www.coursera.org/learn/unix) course by [John Hopkins University](https://www.jhu.edu).">> README.md
	echo "This file has ben automatic generated by *make* command running at *`date`*." >> README.md
	echo "The number of *code lines* contained in file **guessinggame.sh** is: `cat guessinggame.sh | wc -l`." >> README.md
	
clean:
	rm -f README.md
